WebApplication1/Controllers/ExpenseController.cs
using AutoMapper;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using System.Security.Claims;
using ThriftinessCore.Entites;
using ThriftinessCore.Entites.Identity;
using ThriftinessCore.Repos;
using ThriftinessCore.Specfictions;
using ThriftinessRepository.Repos;
using WebApplication1.ViewModel;

namespace WebApplication1.Controllers
{
    public class ExpenseController : Controller
    {
        private readonly IUnitOfWork _unitOfWork;
        private readonly IMapper _mapper;
        private readonly UserManager<AppUser> _userManager;

        public ExpenseController(IUnitOfWork unitOfWork, IMapper mapper, UserManager<AppUser> userManager)
        {
            _unitOfWork = unitOfWork;
            _mapper = mapper;
            _userManager = userManager;
        }

        public async Task<IActionResult> Index(string searchValue, bool? yourBooleanValue)
        {
            var userEmail = User.FindFirstValue(ClaimTypes.Email);
            var user = await _userManager.FindByEmailAsync(userEmail);
            IReadOnlyList<Expense> expenses;
            if (yourBooleanValue != null)
            {
                var checkPriority = new ExppenseSpecfPriorty(yourBooleanValue.Value, user.Id);
                expenses = await _unitOfWork.Repository<Expense>().GetAllWithSpecAsync(checkPriority);
            }
            else if (!string.IsNullOrEmpty(searchValue))
            {
                var checkName = new ExppenseSpecfName(searchValue, user.Id);
                expenses = await _unitOfWork.Repository<Expense>().GetAllWithSpecAsync(checkName);
            }
            else
            {
                var specUser = new ExpenseSpecfUser(user.Id);
                expenses = await _unitOfWork.Repository<Expense>().GetAllWithSpecAsync(specUser);
            }
            user.TotalExpense = user.MonthlySalary - expenses.Sum(o => o.AmountMoney);

            await _userManager.UpdateAsync(user);
            await _unitOfWork.CompleteAsync();

            var mappedResults = _mapper.Map<IEnumerable<ExpenseVM>>(expenses);

            return View(mappedResults);
        }

        public IActionResult Create()
        {
            return View();
        }

        [HttpPost]
        public async Task<IActionResult> Createe(ExpenseVM model)
        {
            if (ModelState.IsValid)
            {
                try
                {
                    var userEmail = User.FindFirstValue(ClaimTypes.Email);
                    var user = await _userManager.FindByEmailAsync(userEmail);
                    var checkMonth = new MonthOfExpenseSpecfNum(DateTime.Today.Month, user.Id);
                    var checkMonthOfExpense = await _unitOfWork.Repository<MonthOfExpense>().GetAllWithSpecAsync(checkMonth);
                    var expense = new Expense()
                    {
                        Title = model.Title,
                        AmountMoney = model.AmountMoney,
                        Priority = model.Priority,
                        UserId = user.Id,
                        ExpenseDate = DateTime.Now,
                        MonthOfExpenseId = checkMonthOfExpense.FirstOrDefault().Id
                    };
                    await _unitOfWork.Repository<Expense>().AddAsync(expense);
                    var month = await _unitOfWork.Repository<MonthOfExpense>().GetbyIdAsync(expense.MonthOfExpenseId);
                    month.TotalAmountMoney = month.TotalAmountMoney + model.AmountMoney;
                    _unitOfWork.Repository<MonthOfExpense>().Update(month);

                    await _unitOfWork.CompleteAsync();
                    return RedirectToAction("Index");
                }
                catch (Exception)
                {
                    return View("Create", model);
                }
            }
            else
            {
                // If model state is not valid, return the view with validation errors
                return View("Create", model);
            }
        }

        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
                return BadRequest();
            var monthOfExpense = await _unitOfWork.Repository<Expense>().GetbyIdAsync(id.Value);
            await _unitOfWork.CompleteAsync();
            var mappedResults = _mapper.Map<ExpenseVM>(monthOfExpense);
            return View(mappedResults);
        }

        [HttpPost]
        public async Task<IActionResult> Edit(ExpenseVM model)
        {
            if (ModelState.IsValid)
            {
                try
                {
                    var mappedResults = _mapper.Map<Expense>(model);
                    _unitOfWork.Repository<Expense>().Update(mappedResults);
                    await _unitOfWork.CompleteAsync();
                    return RedirectToAction("Index");
                }
                catch (Exception)
                {
                    return View(model);
                }
            }
            else
            {
                // If model state is not valid, return the view with validation errors
                return View(model);
            }
        }

        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
                return BadRequest();
            var monthOfExpense = await _unitOfWork.Repository<Expense>().GetbyIdAsync(id.Value);
            await _unitOfWork.CompleteAsync();
            var mappedResults = _mapper.Map<ExpenseVM>(monthOfExpense);
            return View(mappedResults);
        }

        [HttpPost]
        public async Task<IActionResult> Delete(ExpenseVM model)
        {
            if (ModelState.IsValid)
            {
                try
                {
                    var mappedResults = _mapper.Map<Expense>(model);
                    _unitOfWork.Repository<Expense>().DeleteAsync(mappedResults);
                    await _unitOfWork.CompleteAsync();
                    return RedirectToAction("Index");
                }
                catch (Exception)
                {
                    return View(model);
                }
            }
            else
            {
                // If model state is not valid, return the view with validation errors
                return View(model);
            }
        }
    }
}

WebApplication1/Controllers/MonthOfExpenseController.cs
using AutoMapper;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using System.Security.Claims;
using ThriftinessCore.Entites;
using ThriftinessCore.Entites.Identity;
using ThriftinessCore.Repos;
using ThriftinessCore.Specfictions;
using WebApplication1.ViewModel;

namespace WebApplication1.Controllers
{
    [Authorize]
    public class MonthOfExpenseController : Controller
    {
        private readonly IUnitOfWork _unitOfWork;
        private readonly IMapper _mapper;
        private readonly UserManager<AppUser> _userManager;

        public MonthOfExpenseController(IUnitOfWork unitOfWork, IMapper mapper, UserManager<AppUser> userManager)
        {
            _unitOfWork = unitOfWork;
            _mapper = mapper;
            _userManager = userManager;
        }

        public async Task<IActionResult> Index()
        {
            var userEmail = User.FindFirstValue(ClaimTypes.Email);
            var user = await _userManager.FindByEmailAsync(userEmail);
            var specmonth = new MonthOfExpenseSpecf(user.Id);

            var monthOfExpense = await _unitOfWork.Repository<MonthOfExpense>().GetAllWithSpecAsync(specmonth);

            user.TotalExpense = user.MonthlySalary - monthOfExpense.Sum(o => o.TotalAmountMoney);

            await _userManager.UpdateAsync(user);
            await _unitOfWork.CompleteAsync();
            var mappedResults = _mapper.Map<IEnumerable<MonthOfExpenseVM>>(monthOfExpense);

            return View(mappedResults);
        }

        private async Task CreateMonthOfExpense()
        {
            var userEmail = User.FindFirstValue(ClaimTypes.Email);
            var user = await _userManager.FindByEmailAsync(userEmail);
            var checkMonth = new MonthOfExpenseSpecfNum(DateTime.Today.Month, user.Id);
            var checkMonthOfExpense = await _unitOfWork.Repository<MonthOfExpense>().GetAllWithSpecAsync(checkMonth);
            if (checkMonthOfExpense.Count == 0)
            {
                var monthofExpense = new MonthOfExpense()
                {
                    numOfMonth = DateTime.Today.Month,
                    User_Id = user.Id,
                    TotalAmountMoney = 0,
                };

                await _unitOfWork.Repository<MonthOfExpense>().AddAsync(monthofExpense);
                await _unitOfWork.CompleteAsync();
            }
        }

        public async Task<IActionResult> DetailsExpenss(int id)
        {
            if (id == null)
                return BadRequest();
            var specmonth = new ExpenseSpecfMonth(id);
            var monthOfExpense = await _unitOfWork.Repository<Expense>().GetAllWithSpecAsync(specmonth);

            await _unitOfWork.CompleteAsync();

            var mappedResults = _mapper.Map<IEnumerable<ExpenseVM>>(monthOfExpense);
            return View(mappedResults);
            //___________________________________ end of method ----------------------------------
        }
    }
}

WebApplication1/Controllers/SaveGoalController.cs
using AutoMapper;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using System.Security.Claims;
using ThriftinessCore.Entites;
using ThriftinessCore.Entites.Identity;
using ThriftinessCore.Repos;
using ThriftinessCore.Specfictions;
using WebApplication1.ViewModel;

namespace WebApplication1.Controllers
{
    public class SaveGoalController : Controller
    {
        private readonly IUnitOfWork _unitOfWork;
        private readonly IMapper _mapper;
        private readonly UserManager<AppUser> _userManager;

        public SaveGoalController(IUnitOfWork unitOfWork, IMapper mapper, UserManager<AppUser> userManager)
        {
            _unitOfWork = unitOfWork;
            _mapper = mapper;
            _userManager = userManager;
        }

        public async Task<IActionResult> Index()
        {
            var userEmail = User.FindFirstValue(ClaimTypes.Email);
            var user = await _userManager.FindByEmailAsync(userEmail);
            var specmonth = new SaveGoalSpecf(user.Id);

            var monthOfExpense = await _unitOfWork.Repository<SaveGoal>().GetAllWithSpecAsync(specmonth);
            await _unitOfWork.CompleteAsync();

            var mappedResults = _mapper.Map<IEnumerable<SaveGoalVM>>(monthOfExpense);

            return View(mappedResults);
        }

        public IActionResult Create()
        {
            return View();
        }

        [HttpPost]
        public async Task<IActionResult> Createe(SaveGoalVM model)
        {
            if (ModelState.IsValid)
            {
                try
                {
                    var userEmail = User.FindFirstValue(ClaimTypes.Email);
                    var user = await _userManager.FindByEmailAsync(userEmail);
                    var saveGoal = new SaveGoal()
                    {
                        TargetAmount = model.TargetAmount,
                        TitleGoal = model.TitleGoal,
                        User_Id = user.Id
                    };
                    await _unitOfWork.Repository<SaveGoal>().AddAsync(saveGoal);
                    await _unitOfWork.CompleteAsync();
                    return RedirectToAction("Index");
                }
                catch (Exception)
                {
                    return View(model);
                }
            }
            else
            {
                // If model state is not valid, return the view with validation errors
                return View("Create", model);
            }
        }

        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
                return BadRequest();
            var saveGoal = await _unitOfWork.Repository<SaveGoal>().GetbyIdAsync(id.Value);
            await _unitOfWork.CompleteAsync();
            var mappedResults = _mapper.Map<SaveGoalVM>(saveGoal);
            return View(mappedResults);
        }

        [HttpPost]
        public async Task<IActionResult> Edit(SaveGoalVM model)
        {
            if (ModelState.IsValid)
            {
                try
                {
                    var mappedResults = _mapper.Map<SaveGoal>(model);
                    _unitOfWork.Repository<SaveGoal>().Update(mappedResults);
                    await _unitOfWork.CompleteAsync();
                    return RedirectToAction("Index");
                }
                catch (Exception)
                {
                    return View(model);
                }
            }
            else
            {
                // If model state is not valid, return the view with validation errors
                return View(model);
            }
        }

        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
                return BadRequest();
            var saveGoal = await _unitOfWork.Repository<SaveGoal>().GetbyIdAsync(id.Value);
            await _unitOfWork.CompleteAsync();
            var mappedResults = _mapper.Map<SaveGoalVM>(saveGoal);
            return View(mappedResults);
        }

        [HttpPost]
        public async Task<IActionResult> Delete(SaveGoalVM model)
        {
            if (ModelState.IsValid)
            {
                try
                {
                    var mappedResults = _mapper.Map<SaveGoal>(model);
                    _unitOfWork.Repository<SaveGoal>().DeleteAsync(mappedResults);
                    await _unitOfWork.CompleteAsync();
                    return RedirectToAction("Index");
                }
                catch (Exception)
                {
                    return View(model);
                }
            }
            else
            {
                // If model state is not valid, return the view with validation errors
                return View(model);
            }
        }
    }
}

WebApplication1/Controllers/UserSettingsController.cs
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using System.Security.Claims;
using ThriftinessCore.Entites.Identity;
using WebApplication1.Helper;
using WebApplication1.ViewModel;

namespace WebApplication1.Controllers
{
    public class UserSettingsController : Controller
    {
        private readonly UserManager<AppUser> _userManager;

        public UserSettingsController(UserManager<AppUser> userManager)
        {
            _userManager = userManager;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult AddMonthlySalary()
        {
            return View();
        }

        [HttpPost]
        public async Task<IActionResult> AddMonthlySalary(UserSettingsVM model)
        {
            var userEmail = User.FindFirstValue(ClaimTypes.Email);
            var user = await _userManager.FindByEmailAsync(userEmail);
            user.MonthlySalary = model.MonthlySalary;
            await _userManager.UpdateAsync(user);
            return RedirectToAction("Index");
        }

        public IActionResult AddDayOfEndMonth()
        {
            return View();
        }

        [HttpPost]
        public async Task<IActionResult> AddDayOfEndMonth(UserSettingsVM model)
        {
            var userEmail = User.FindFirstValue(ClaimTypes.Email);
            var user = await _userManager.FindByEmailAsync(userEmail);
            user.DayOfEndMonth = model.DayOfEndMonth;
            await _userManager.UpdateAsync(user);
            return RedirectToAction("Index");
        }
    }
}

WebApplication1/Views/Shared/_AuthLayout.cshtml
<!DOCTYPE html>
<html>
<head>
	<meta charset="UTF-8">
	<title>@ViewData["Title"]</title>
	<link rel="icon" href="~/imges/download.png">
	<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/animate.css/4.1.1/animate.min.css" />
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Anton&family=EB+Garamond:wght@800&family=Lobster&family=Poppins:ital,wght@0,100;0,200;0,300;0,400;0,500;0,600;0,700;0,800;0,900;1,100;1,200;1,300;1,400;1,500;1,600;1,700;1,800;1,900&family=Quicksand:wght@600&family=Roboto:wght@300&display=swap" rel="stylesheet">
    <link href="~/lib/bootstrap/dist/css/bootstrap.min.css" rel="stylesheet" />
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/meyer-reset/2.0/reset.min.css">
    <link href="~/css/authstyle.css" rel="stylesheet" />
</head>
<body>
	<!-- main -->

    <div class="arrow arrow--top">
        <svg xmlns="http://www.w3.org/2000/svg" width="270.11" height="649.9" overflow="visible">
            <style>
                .geo-arrow {
                    fill: none;
                    stroke: #fff;
                    stroke-width: 2;
                    stroke-miterlimit: 10
                }
            </style>
            <g class="item-to bounce-1">
                <path class="geo-arrow draw-in" d="M135.06 142.564L267.995 275.5 135.06 408.434 2.125 275.499z" />
            </g>
            <circle class="geo-arrow item-to bounce-2" cx="194.65" cy="69.54" r="7.96" />
            <circle class="geo-arrow draw-in" cx="194.65" cy="39.5" r="7.96" />
            <circle class="geo-arrow item-to bounce-3" cx="194.65" cy="9.46" r="7.96" />
            <g class="geo-arrow item-to bounce-2">
                <path class="st0 draw-in" d="M181.21 619.5l13.27 27 13.27-27zM194.48 644.5v-552" />
            </g>
        </svg>
    </div>
    <div class="arrow arrow--bottom">
        <svg xmlns="http://www.w3.org/2000/svg" width="31.35" height="649.9" overflow="visible">
            <style>
                .geo-arrow {
                    fill: none;
                    stroke: #fff;
                    stroke-width: 2;
                    stroke-miterlimit: 10
                }
            </style>
            <g class="item-to bounce-1">
                <circle class="geo-arrow item-to bounce-3" cx="15.5" cy="580.36" r="7.96" />
                <circle class="geo-arrow draw-in" cx="15.5" cy="610.4" r="7.96" />
                <circle class="geo-arrow item-to bounce-2" cx="15.5" cy="640.44" r="7.96" />
                <g class="item-to bounce-2">
                    <path class="geo-arrow draw-in" d="M28.94 30.4l-13.26-27-13.27 27zM15.68 5.4v552" />
                </g>
            </g>
        </svg>
    </div>
    <div class="main">

		@RenderBody()

    </div>

    <!-- //main -->
 
    <script src="~/lib/bootstrap/dist/js/bootstrap.min.js"></script>

	@await RenderSectionAsync("ValidtionForm", required: false)
</body>
</html>

WebApplication1/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - WebApplication1</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.4.2/css/all.min.css" integrity="sha512-z3gLpd7yknf1YoNbCzqRKc4qyor8gaKU1qmn+CShxbuBusANI9QpRohGBreCFkKxLhei6S9CQXFEbbKuqLg0DA==" crossorigin="anonymous" referrerpolicy="no-referrer" />
    <link rel="icon" href="~/imges/download.png">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/animate.css/4.1.1/animate.min.css" />
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/meyer-reset/2.0/reset.min.css">

    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/WebApplication1.styles.css" asp-append-version="true" />
</head>
<body>
    <div id="loading-screen">
    <div id="particles-background" class="vertical-centered-box"></div>
    <div id="particles-foreground" class="vertical-centered-box"></div>

    <div class="vertical-centered-box">
        <div class="content">
            <div class="loader-circle"></div>
            <div class="loader-line-mask">
                <div class="loader-line"></div>
            </div>
                <img src="~/imges/download.png" width="120px" alt="home page">
        </div>
    </div>
    </div>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-transparent bg-navbar  mb-3 fixed-top bg-nav">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index"><img src="~/imges/download.png"  class="img-fluid img-nav"/></a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="collapse navbar-collapse">
                    <div class="container dir-navbar">


                        <ul class="navbar-nav dir-navbar ml-auto text-center">
                        <li class="nav-item">
                                <a class="nav-link text-light alink" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                    
                        <li class="nav-item">
                                <a class="nav-link text-light alink" asp-area="" asp-controller="MonthOfExpense" asp-action="Index">MonthOfExpense</a>
                        </li>
                        <li class="nav-item">
                                <a class="nav-link text-light alink" asp-area="" asp-controller="Expense" asp-action="Index">Expense</a>
                        </li>
                        <li class="nav-item">
                                <a class="nav-link text-light alink" asp-area="" asp-controller="SaveGoal" asp-action="Index">Goal</a>
                        </li>
                        <li class="nav-item">
                                <a class="nav-link text-light alink" asp-area="" asp-controller="UserSettings" asp-action="Index">Settings</a>
                        </li>
                       
                    </ul>
                    </div>
                </div>
            </div>
        </nav>
    </header>

    <main role="main" class="container min-header">
            @RenderBody()
        </main>
 

    <footer class="border-top footer text-muted">
        <div class="container text-color">
            &copy; 2024 - Thriftiness - <a asp-area="" asp-controller="Home" asp-action="Index" class="a-auth">Home</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>


    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>